language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install .
  - pip install pytest-cov coveralls sphinx_rtd_theme
# command to run tests
script:
  py.test --cov=ostrich
# commands to run after success
after_success:
  coveralls
